import type { CarPartsConfig } from "../types";

export const W204_C63: CarPartsConfig = {
  carKey: "w204-c63-amg",
  matchCriteria: { make: "Mercedes-Benz", model: "C63" },
  displayName: "2013 Mercedes-Benz C63 AMG (W204)",
  baseStats: {
    hp: 487,
    torque: 443,
    weight: 3858,
    zeroToSixty: 4.4,
    quarterMile: 12.8,
    quarterMileSpeed: 112,
  },
  categories: [
    "tuning",
    "transmission",
    "package",
    "forced-induction",
    "exhaust",
    "intake",
    "engine",
    "fueling",
    "cooling",
    "drivetrain",
    "brakes",
    "exterior",
  ],
  parts: [
    // ═══════════════════════════════════════════════════════════════
    // TUNING
    // ═══════════════════════════════════════════════════════════════
    {
      id: "ec-ppp-stage1",
      category: "tuning",
      type: "Performance",
      name: "Stage 1 ECU Tune — Mercedes C 63 AMG PPP",
      brand: "Eurocharged",
      description:
        "Entry-level ECU calibration for the C63 AMG P31 Performance Package. Optimized timing and AFR for stock hardware.",
      price: 999,
      hpGain: 63,
      torqueGain: 50,
      productUrl: "https://www.eurocharged.com/product/mercedes-c63-amg-ecu-tune-2?srsltid=AfmBOoo7QHsrZ4iU4Njd4OF3yOWfpYlQsE7fxFsyx3iK7mlygXrr-J_I",
      imageUrl: null,
    },
    {
      id: "ec-ppp-stage2",
      category: "tuning",
      type: "Performance",
      name: "Stage 2 ECU Tune — Mercedes C 63 AMG PPP",
      brand: "Eurocharged",
      description:
        "Aggressive stage 2 calibration for the C63 AMG P31 Performance Package. Requires aftermarket intake and exhaust.",
      price: 1099,
      hpGain: 88,
      torqueGain: 69,
      productUrl: "https://www.eurocharged.com/product/mercedes-c63-amg-ecu-tune-2?srsltid=AfmBOoo7QHsrZ4iU4Njd4OF3yOWfpYlQsE7fxFsyx3iK7mlygXrr-J_I",
      imageUrl: null,
    },
    {
      id: "rt-hht",
      category: "tuning",
      type: "Performance",
      name: "ECU Hand Held Tuner (HHT)",
      brand: "RENNtech",
      description:
        "Handheld OBD2 flash tool delivering proprietary AMG-developed timing maps. +66 HP / +42 TQ.",
      price: 1640,
      hpGain: 66,
      torqueGain: 42,
      productUrl: "https://www.vividracing.com/renntech-ecu-hand-held-tuner-for-mercedesbenz-c63-amg-63l-w204-20082015-517hp-485lbft-p-157075177.html",
      imageUrl: null,
    },
    {
      id: "vr-tuned",
      category: "tuning",
      type: "Performance",
      name: "VR Tuned ECU Flash",
      brand: "Vivid Racing",
      description:
        "Alternative digital tuning prioritizing sharp throttle response and top-end delivery.",
      price: 1500,
      hpGain: null,
      torqueGain: null,
      specs: "Throttle response + top-end optimization",
      productUrl: "https://www.vividracing.com/mercedes-c63-tuning-i-176.html",
      imageUrl: null,
    },
    {
      id: "ws-ecu",
      category: "tuning",
      type: "Performance",
      name: "M156 ECU Tune",
      brand: "Weistec",
      description:
        "Baseline software optimization for the naturally aspirated M156 platform.",
      price: 809.10,
      hpGain: 47,
      torqueGain: 32,
      productUrl: "https://www.weistec.com/product-list.html",
      imageUrl: null,
    },

    // ═══════════════════════════════════════════════════════════════
    // TRANSMISSION
    // ═══════════════════════════════════════════════════════════════
    {
      id: "ec-tcu",
      category: "transmission",
      type: "Performance",
      name: "TCU Tune",
      brand: "Eurocharged",
      description:
        "Transmission control unit tune unlocking higher torque limits through the gearbox for faster, harder shifts.",
      price: 499,
      hpGain: null,
      torqueGain: null,
      specs: "20–30% increase in TCU TQ limits",
      productUrl: "https://www.eurocharged.com/product/19",
      imageUrl: null,
    },

    // ═══════════════════════════════════════════════════════════════
    // PACKAGES (RENNtech bundled tiers)
    // ═══════════════════════════════════════════════════════════════
    {
      id: "rt-stage3-pkg",
      category: "package",
      type: "Performance",
      name: "Stage 3 Power Package",
      brand: "RENNtech",
      description:
        "Ultimate NA suite: ECU flash, CF Airbox, 82mm Throttle Body, Long Tube Headers, LSD, and trans upgrade.",
      price: 21520,
      hpGain: 87,
      torqueGain: 100,
      productUrl: "https://autotalent.com/products/renntech-r3-performance-package-for-mercedes-benz-w204-c63-amg-2008-2014",
      imageUrl: null,
    },
    {
      id: "vrp-stage1-pkg",
      category: "package",
      type: "Performance",
      name: "VRP530 Stage 1 Power Package (M156)",
      brand: "VRP",
      description:
        "Entry-level bolt-on power bundle for the M156: long tube headers, intake tubes, ROW airboxes, and an ECU tune.",
      price: 1800,
      hpGain: 43,
      torqueGain: 47,
      productUrl: "https://www.vrpspeed.com/product/stage1kit-2/",
      imageUrl: null,
    },
    {
      id: "vrp-stage2-pkg",
      category: "package",
      type: "Performance",
      name: "VRP540 Stage 2 Power Package (M156)",
      brand: "VRP",
      description:
        "Comprehensive stage 2 system building on Stage 1 with additional upgrades for significant wheel horsepower gains.",
      price: 3000,
      hpGain: 63,
      torqueGain: 72,
      productUrl: "https://www.vrpspeed.com/product/stage2kit-2/",
      imageUrl: null,
    },
    {
      id: "vrp-stage3-pkg",
      category: "package",
      type: "Performance",
      name: "VRP575 Stage 3 Power Package (M156)",
      brand: "VRP",
      description:
        "High-output naturally aspirated package pushing the M156 platform to its atmospheric limits.",
      price: 4350,
      hpGain: 88,
      torqueGain: 87,
      productUrl: "https://www.vrpspeed.com/product-category/63-amg-m156-6-2l/",
      imageUrl: null,
    },
    {
      id: "vrp-stage4-pkg",
      category: "package",
      type: "Performance",
      name: "VRP600 Stage 4 Power Package (M156)",
      brand: "VRP",
      description:
        "Ultimate naturally aspirated M156 package squeezing maximum displacement from every cubic centimeter.",
      price: 6500,
      hpGain: 113,
      torqueGain: 107,
      productUrl: "https://www.vrpspeed.com/product/stage4kit-2/",
      imageUrl: null,
    },

    // ═══════════════════════════════════════════════════════════════
    // FORCED INDUCTION
    // ═══════════════════════════════════════════════════════════════
    {
      id: "ws-sc-stage1",
      category: "forced-induction",
      type: "Performance",
      name: "Stage 1 Supercharger System",
      brand: "Weistec",
      description:
        "Twin-screw positive displacement supercharger engineered for factory internal limits. Bolt-on.",
      price: 11999,
      hpGain: 186,
      torqueGain: 117,
      productUrl: "https://www.weistec.com/stage-1-m156-supercharger-system.html",
      imageUrl: null,
    },
    {
      id: "ws-sc-stage3",
      category: "forced-induction",
      type: "Performance",
      name: "Stage 3 Supercharger System",
      brand: "Weistec",
      description:
        "Maximum forced induction capability utilizing high-volume displacement twin-screw rotors.",
      price: 15599,
      hpGain: 289,
      torqueGain: 187,
      productUrl: "https://www.weistec.com/stage-3-m156-supercharger-system.html",
      imageUrl: null,
    },
    {
      id: "ws-sc-upgrade",
      category: "forced-induction",
      type: "Performance",
      name: "Stage 1 to 3 Upgrade Kit",
      brand: "Weistec",
      description:
        "Hardware expansion pathway upgrading Stage 1 to Stage 3 displacement. Includes high-rate tensioners and advanced fluid cooling.",
      price: 7899,
      hpGain: 289,
      torqueGain: 187,
      requiresPartIds: ["ws-sc-stage1"],
      productUrl: "https://www.weistec.com/stage-1-2-to-stage-3-supercharger-upgrade-m156.html",
      imageUrl: null,
    },
    {
      id: "vrp-30l-sc",
      category: "forced-induction",
      type: "Performance",
      name: "Gen 5 3.0L Whipple Supercharger Kit",
      brand: "VRP",
      description:
        "Complete bolt-on supercharger system with Gen 5 Whipple, dual Hellcat intercoolers, billet manifolds, fuel rail, inlet tubes, and all hardware. Dyno tested at 659 WHP / 611 WTQ on 93 octane.",
      price: 12499,
      hpGain: 220,
      torqueGain: 126,
      specs: "659 WHP / 611 WTQ peak · 294+ WHP over stock",
      productUrl: "https://www.vrpspeed.com/product/vrp-m156-supercharger-upgrade-kit/",
      imageUrl: null,
    },

    // ═══════════════════════════════════════════════════════════════
    // EXHAUST
    // ═══════════════════════════════════════════════════════════════
    {
      id: "vrp-lth",
      category: "exhaust",
      type: "Performance",
      name: "63 AMG Long Tube Headers (M156)",
      brand: "VRP",
      description:
        "Equal-length long tube headers maximizing exhaust scavenging across the full RPM range. Significant mid and top-end gains.",
      price: { min: 1200, max: 1800 },
      hpGain: 39,
      torqueGain: 34,
      productUrl: "https://www.vrpspeed.com/product/m156-63amg-longtube-headers/?srsltid=AfmBOoqJNNJwmype-f_Q9A8a5jQEz4142jzjl5BVLznJbwLOPRvnZ1__",
      imageUrl: null,
    },
    {
      id: "ak-slipon",
      category: "exhaust",
      type: "Performance",
      name: "Slip-On Line (Titanium)",
      brand: "Akrapovic",
      description:
        "Aerospace-grade titanium rear axle-back mufflers reducing unsprung mass by 8.5 kg (18.7 lbs).",
      price: { min: 2000, max: 4288 },
      hpGain: 5,
      torqueGain: null,
      specs: "-8.5 kg unsprung weight",
      productUrl: "https://www.akrapovic.com/en/car/product/91/Mercedes-AMG/C-63-Sedan-C-63-Estate-W204-S204/2012?brandId=25&modelId=77&yearId=302",
      imageUrl: null,
    },
    {
      id: "ak-evo",
      category: "exhaust",
      type: "Performance",
      name: "Evolution Line Titanium Cat Back",
      brand: "Akrapovic",
      description:
        "Full titanium system including link pipes. Drastic weight loss (-13 to 19 kg) and profound acoustics.",
      price: { min: 7801.50, max: 9152.32 },
      hpGain: 12,
      torqueGain: 16,
      productUrl: "https://www.akrapovic.com/en/car/product/739/Mercedes-AMG/C-63-Sedan-C-63-Estate-W204-S204/2014?brandId=25&modelId=77&yearId=304",
      imageUrl: null,
    },
    {
      id: "fab-valvetronic",
      category: "exhaust",
      type: "Performance",
      name: "Valvetronic Sport Exhaust System",
      brand: "Fabspeed",
      description:
        "Advanced valved exhaust allowing dynamic routing between straight-pipe and muffled states.",
      price: { min: 3999, max: 5999 },
      hpGain: null,
      torqueGain: null,
      specs: "Acoustic versatility — quiet to race mode",
      productUrl: "https://www.fabspeed.com/other-makes-models/mercedes-benz/c-class/",
      imageUrl: null,
    },
    {
      id: "fmu-xpipe",
      category: "exhaust",
      type: "Performance",
      name: "Race Midsection with X-Pipe",
      brand: "Fluid MotorUnion",
      description:
        "Replaces primary resonator with a smooth-merge X-pipe, removing exhaust restrictions.",
      price: 699,
      hpGain: null,
      torqueGain: null,
      specs: "Flow equalization between banks",
      productUrl: "https://fluidmotorunion.com/product/w204-c63-exhaust-race-midsection-with-x-pipe/",
      imageUrl: null,
    },

    // ═══════════════════════════════════════════════════════════════
    // INTAKE
    // ═══════════════════════════════════════════════════════════════
    {
      id: "vrp-throttle-body",
      category: "intake",
      type: "Performance",
      name: "Throttle Body Upgrade Kit (M156)",
      brand: "VRP",
      description:
        "High-flow throttle body upgrade increasing air volume entering the M156 for improved throttle response and power.",
      price: 1600,
      hpGain: 12,
      torqueGain: 8,
      productUrl: "https://www.vrpspeed.com/product/vrpm156tb/?srsltid=AfmBOorr-NbJzBMAjnf_rDxGmuVCoH2lEb8c3wwq-bqdFns9dkqBR_Bl",
      imageUrl: null,
    },
    {
      id: "vrp-intake-tubes",
      category: "intake",
      type: "Performance",
      name: "63 AMG Intake Tubes (M156)",
      brand: "VRP",
      description:
        "Mandrel-bent intake tubes replacing the factory restrictive plastic units for improved airflow to the throttle bodies.",
      price: { min: 300, max: 500 },
      hpGain: null,
      torqueGain: null,
      specs: "Improved airflow velocity",
      productUrl: "https://www.vrpspeed.com/product/vrp-intake-tubes-m156/",
      imageUrl: null,
    },
    {
      id: "vrp-row-airboxes",
      category: "intake",
      type: "Performance",
      name: "M156 ROW Airboxes",
      brand: "VRP",
      description:
        "European-spec (ROW) airboxes fitted to the M156, allowing more aggressive cold air feeding to both banks.",
      price: 700,
      hpGain: 8,
      torqueGain: null,
      specs: "5–10 HP gain",
      productUrl: "https://www.vrpspeed.com/product/m156-row-airboxes/",
      imageUrl: null,
    },
    {
      id: "ev-v2-duct",
      category: "intake",
      type: "Performance",
      name: "Black Carbon V2 Duct Upgrade",
      brand: "Eventuri",
      description:
        "Carbon fiber ducting to direct high-velocity cold air directly into the throttle bodies.",
      price: 215,
      hpGain: null,
      torqueGain: null,
      specs: "Inlet temperature reduction",
      productUrl: "https://www.fabspeed.com/eventuri-mercedes-w205-c63-c63s-amg-black-carbon-intake-v2/",
      imageUrl: null,
    },

    // ═══════════════════════════════════════════════════════════════
    // ENGINE INTERNALS
    // ═══════════════════════════════════════════════════════════════
    {
      id: "ws-ported-heads",
      category: "engine",
      type: "Performance",
      name: "CNC Ported Heads",
      brand: "Weistec",
      description:
        "Machine-ported cylinder heads to maximize laminar airflow into the combustion chamber.",
      price: 5699,
      hpGain: null,
      torqueGain: null,
      specs: "Maximum volumetric efficiency",
      productUrl: "https://www.weistec.com/product-list.html",
      imageUrl: null,
    },
    {
      id: "ws-tensioner",
      category: "engine",
      type: "Performance",
      name: "High Rate Tensioner",
      brand: "Weistec",
      description:
        "Custom modified tensioner applying greater force to prevent supercharger belt slip.",
      price: { min: 200, max: 400 },
      hpGain: null,
      torqueGain: null,
      specs: "Belt stability under high load",
      productUrl: "https://www.weistec.com/m156-high-rate-tensioner.html",
      imageUrl: null,
    },
    {
      id: "vrp-pulley-kit",
      category: "engine",
      type: "Performance",
      name: "M156 5-Piece Pulley Kit",
      brand: "VRP",
      description:
        "Replaces factory plastic idlers with billet aluminum units, preventing catastrophic belt failures.",
      price: 492.99,
      hpGain: null,
      torqueGain: null,
      specs: "Accessory drive reliability",
      productUrl: "https://www.vrpspeed.com/product-category/63-amg-m156-6-2l/",
      imageUrl: null,
    },
    {
      id: "vrp-lifters",
      category: "engine",
      type: "Performance",
      name: "Lifter Replacement Kit M156",
      brand: "VRP",
      description:
        "Upgraded Black Series-style lifters to prevent standard M156 cam lobe wear issues.",
      price: 1299,
      hpGain: null,
      torqueGain: null,
      specs: "Valvetrain integrity",
      productUrl: "https://www.vrpspeed.com/product/lifter-replacement-kit-m156/",
      imageUrl: null,
    },
    {
      id: "vrp-phaser",
      category: "engine",
      type: "Performance",
      name: "M156 Phaser Rebuild Program",
      brand: "VRP",
      description:
        "Upgraded sealing rings and rebuilding of the notoriously weak M156 cam phasers.",
      price: { min: 800, max: 1800 },
      hpGain: null,
      torqueGain: null,
      specs: "Timing integrity",
      productUrl: "https://www.vrpspeed.com/product/vrp-m156-complete-phaser-upgrade-rebuild-program-set-of-4/",
      imageUrl: null,
    },
    {
      id: "vrp-pistons",
      category: "engine",
      type: "Performance",
      name: "Diamond Racing Pistons (M156)",
      brand: "VRP",
      description:
        "Forged pistons built to withstand immense cylinder pressures and heat from supercharging.",
      price: 1835.79,
      hpGain: null,
      torqueGain: null,
      specs: "Boost compression management",
      productUrl: "https://www.vrpspeed.com/product/diamond-racing-pistons-mercedes-m156/",
      imageUrl: null,
    },
    {
      id: "vrp-catchcan",
      category: "engine",
      type: "Performance",
      name: "Oil Catch Can Kit",
      brand: "VRP",
      description:
        "Intercepts oil vapors from crankcase ventilation, preventing intake manifold coating.",
      price: 324.99,
      hpGain: null,
      torqueGain: null,
      specs: "Blow-by prevention",
      productUrl: "https://www.vrpspeed.com/product-category/63-amg-m156-6-2l/",
      imageUrl: null,
    },

    // ═══════════════════════════════════════════════════════════════
    // FUELING
    // ═══════════════════════════════════════════════════════════════
    {
      id: "vrp-fuel-system",
      category: "fueling",
      type: "Performance",
      name: "Stage X Dual Return Fuel System",
      brand: "VRP",
      description:
        "Complete fuel delivery overhaul required for safe stoichiometric fueling during high-boost.",
      price: 2999,
      hpGain: null,
      torqueGain: null,
      specs: "High-volume supply for 600+ HP",
      productUrl: "https://www.vrpspeed.com/product-category/63-amg-m156-6-2l/",
      imageUrl: null,
    },
    {
      id: "vrp-injectors",
      category: "fueling",
      type: "Performance",
      name: "Hi Flow 630cc Fuel Injectors",
      brand: "VRP",
      description:
        "Large capacity injectors to atomize required fuel volumes for boosted platforms.",
      price: { min: 500, max: 900 },
      hpGain: null,
      torqueGain: null,
      specs: "AFR management for forced induction",
      productUrl: "https://www.vrpspeed.com/product/m156-hi-flow-630cc-fuel-injectors/",
      imageUrl: null,
    },

    // ═══════════════════════════════════════════════════════════════
    // COOLING
    // ═══════════════════════════════════════════════════════════════
    {
      id: "vrp-cooling-kit",
      category: "cooling",
      type: "Performance",
      name: "Mercedes Stage 1 Cooling Kit",
      brand: "VRP",
      description:
        "Split cooling system isolating intercooler fluid from the main engine heat circuit.",
      price: 425.78,
      hpGain: null,
      torqueGain: null,
      specs: "Thermal heat extraction",
      productUrl: "https://www.vrpspeed.com/product-category/63-amg-m156-6-2l/",
      imageUrl: null,
    },
    {
      id: "vrp-heat-exchanger",
      category: "cooling",
      type: "Performance",
      name: "PLM Direct Fit Heat Exchanger",
      brand: "VRP",
      description:
        "High-capacity heat exchanger mounting behind the bumper without structural cuts.",
      price: 389,
      hpGain: null,
      torqueGain: null,
      specs: "Fluid temperature reduction",
      productUrl: "https://www.vrpspeed.com/product-category/63-amg-m156-6-2l/",
      imageUrl: null,
    },
    {
      id: "vrp-cooling-pump",
      category: "cooling",
      type: "Performance",
      name: "Superflo Cooling Pump",
      brand: "VRP",
      description:
        "High-velocity fluid pump ensuring rapid circulation through the intercooler core.",
      price: 495,
      hpGain: null,
      torqueGain: null,
      specs: "Fluid temperature reduction",
      productUrl: "https://www.vrpspeed.com/product-category/63-amg-m156-6-2l/",
      imageUrl: null,
    },

    // ═══════════════════════════════════════════════════════════════
    // DRIVETRAIN
    // ═══════════════════════════════════════════════════════════════
    {
      id: "ws-axles",
      category: "drivetrain",
      type: "Performance",
      name: "1000hp Extreme Duty Race Axles",
      brand: "Weistec",
      description:
        "Heavy-duty shafts designed to handle high-horsepower shock loads without snapping.",
      price: 2299,
      hpGain: null,
      torqueGain: null,
      specs: "Anti-shear protection",
      productUrl: "https://www.weistec.com/product-list.html",
      imageUrl: null,
    },
    {
      id: "vrp-diff-kit",
      category: "drivetrain",
      type: "Performance",
      name: "Diff. Bearing & Seal Kit",
      brand: "VRP",
      description:
        "Overhaul kit for the rear axle assembly handling massive torque loads.",
      price: 335,
      hpGain: null,
      torqueGain: null,
      specs: "Mechanical reliability",
      productUrl: "https://www.vrpspeed.com/product-category/63-amg-m156-6-2l/",
      imageUrl: null,
    },
    {
      id: "vrp-driveshaft",
      category: "drivetrain",
      type: "Performance",
      name: "JXB Driveshaft Center Support",
      brand: "VRP",
      description:
        "Upgraded carrier bearing to prevent driveshaft deflection under extreme acceleration.",
      price: 299.99,
      hpGain: null,
      torqueGain: null,
      specs: "Anti-vibration",
      productUrl: "https://www.vrpspeed.com/product-category/63-amg-m156-6-2l/",
      imageUrl: null,
    },
    {
      id: "rt-cf-strut-bar",
      category: "drivetrain",
      type: "Performance",
      name: "Carbon Fiber Rear Strut Bar",
      brand: "RENNtech",
      description:
        "Lightweight carbon fiber brace connecting the rear strut towers to reduce chassis flex and improve handling precision.",
      price: 995,
      hpGain: null,
      torqueGain: null,
      specs: "Chassis rigidity",
      productUrl: "https://store.renntechmercedes.com/collections/c-63-amg-204-2008-2014/products/renntech-carbon-fiber-rear-strut-bar-w204-c-class",
      imageUrl: null,
    },
    {
      id: "rt-motorsport-suspension",
      category: "drivetrain",
      type: "Performance",
      name: "Motorsport Suspension Package",
      brand: "RENNtech",
      description:
        "Complete track-focused suspension overhaul with adjustable dampers, lowered springs, and upgraded bushings for maximum cornering capability.",
      price: 9400,
      hpGain: null,
      torqueGain: null,
      specs: "Full suspension overhaul",
      productUrl: "http://store.renntechmercedes.com/collections/c-63-amg-204-2008-2014/products/motorsport-suspension-package-for-204-c-class",
      imageUrl: null,
    },

    // ═══════════════════════════════════════════════════════════════
    // BRAKES
    // ═══════════════════════════════════════════════════════════════
    {
      id: "ws-bbk-front",
      category: "brakes",
      type: "Performance",
      name: "Brembo Front BBK (GT-S)",
      brand: "Weistec",
      description:
        "405mm x 34mm heavy-duty brake rotors and multi-piston calipers for immense stopping power.",
      price: 5495,
      hpGain: null,
      torqueGain: null,
      specs: "Thermal fade reduction",
      productUrl: "https://www.weistec.com/product-list.html",
      imageUrl: null,
    },
    {
      id: "ws-bbk-rear",
      category: "brakes",
      type: "Performance",
      name: "Brembo Rear BBK (GT-R)",
      brand: "Weistec",
      description:
        "345mm x 28mm extreme duty rear rotors matching the front bias.",
      price: 8395,
      hpGain: null,
      torqueGain: null,
      specs: "Thermal fade reduction",
      productUrl: "https://www.weistec.com/product-list.html",
      imageUrl: null,
    },

    // ═══════════════════════════════════════════════════════════════
    // EXTERIOR — AERO
    // ═══════════════════════════════════════════════════════════════
    {
      id: "rw-bs-lip",
      category: "exterior",
      type: "Aero",
      name: "Black Series Style CF Front Lip",
      brand: "RW Carbon",
      description:
        "Handcrafted 100% dry carbon fiber front lip mimicking the ultra-rare C63 Black Series.",
      price: 519.95,
      hpGain: null,
      torqueGain: null,
      specs: "Front axle downforce",
      productUrl: "https://www.rwcarbon.com/mercedes-w204-c63-amg-black-series-style-carbon-fiber-front-lip.html",
      imageUrl: null,
    },
    {
      id: "rw-bigfin-diff",
      category: "exterior",
      type: "Aero",
      name: "Big Fin Carbon Fiber Diffuser",
      brand: "RW Carbon",
      description:
        "Aggressive vertical fins direct underbody airflow to reduce trailing aerodynamic drag.",
      price: 439.95,
      hpGain: null,
      torqueGain: null,
      specs: "Wake turbulence reduction",
      productUrl: "https://www.rwcarbon.com/mercedes-w204-c63-amg-c250-c350-big-fin-carbon-fiber-diffuser.html",
      imageUrl: null,
    },
    {
      id: "rw-dtm-diff",
      category: "exterior",
      type: "Aero",
      name: "DTM Carbon Fiber Rear Diffuser",
      brand: "RW Carbon",
      description:
        "DTM racing-inspired rear diffuser replacing the factory plastic unit with genuine 2x2 carbon.",
      price: 459.95,
      hpGain: null,
      torqueGain: null,
      specs: "Wake turbulence reduction",
      productUrl: "https://www.rwcarbon.com/mercedes-c63-amg-dtm-carbon-fiber-diffuser.html",
      imageUrl: null,
    },
    {
      id: "rw-mirrors",
      category: "exterior",
      type: "Cosmetic",
      name: "CF Replacement Mirror Covers",
      brand: "RW Carbon",
      description:
        "Full carbon fiber mirror housings (not overlays), clear-coated for UV protection.",
      price: 399.95,
      hpGain: null,
      torqueGain: null,
      specs: "Aesthetic / weight reduction",
      productUrl: "https://www.rwcarbon.com/mercedes-w204-c63-amg-carbon-fiber-parts.html",
      imageUrl: null,
    },
    {
      id: "rw-roof-spoiler",
      category: "exterior",
      type: "Aero",
      name: "Sedan Carbon Fiber Roof Spoiler",
      brand: "RW Carbon",
      description:
        "Roofline boundary layer disruption piece, deflecting air cleanly off the rear glass.",
      price: 229.95,
      hpGain: null,
      torqueGain: null,
      specs: "Boundary layer disruption",
      productUrl: "https://www.rwcarbon.com/mercedes-w204-c250-c300-c350-c63-carbon-fiber-roof-spoiler.html",
      imageUrl: null,
    },
    {
      id: "rw-dtm-trunk-coupe",
      category: "exterior",
      type: "Aero",
      name: "Coupe DTM Style CF Trunk Spoiler",
      brand: "RW Carbon",
      description:
        "Aggressively styled trunk spoiler interrupting roof airflow to push the driving axle down.",
      price: 269.95,
      hpGain: null,
      torqueGain: null,
      specs: "Rear axle downforce",
      productUrl: "https://www.rwcarbon.com/mercedes-w204-coupe-dtm-style-carbon-fiber-trunk-spoiler.html",
      imageUrl: null,
    },
    {
      id: "rw-amg-trunk-coupe",
      category: "exterior",
      type: "Aero",
      name: "Coupe AMG Style CF Trunk Spoiler",
      brand: "RW Carbon",
      description:
        "OEM AMG-style carbon spoiler providing subtle aerodynamic enhancement and aesthetic matching.",
      price: 199.95,
      hpGain: null,
      torqueGain: null,
      specs: "Aerodynamic flow",
      productUrl: "https://www.rwcarbon.com/mercedes-w204-c250-c300-c350-c63-carbon-fiber-trunk-spoiler.html",
      imageUrl: null,
    },
    {
      id: "rw-skirts",
      category: "exterior",
      type: "Aero",
      name: "C63 CF Side Skirt Extensions",
      brand: "RW Carbon",
      description:
        "Bolted under side skirts to prevent turbulent high-pressure side air from entering under the car.",
      price: 579.95,
      hpGain: null,
      torqueGain: null,
      specs: "Boundary layer management",
      productUrl: "https://www.rwcarbon.com/mercedes-w204-c63-amg-carbon-fiber-side-skirt-extensions.html",
      imageUrl: null,
    },
    {
      id: "rw-dtm-skirts",
      category: "exterior",
      type: "Aero",
      name: "DTM CF Side Skirt Extensions",
      brand: "RW Carbon",
      description:
        "A more pronounced, DTM racing-style side extension for maximum aerodynamic separation.",
      price: 699.95,
      hpGain: null,
      torqueGain: null,
      specs: "Boundary layer management",
      productUrl: "https://www.rwcarbon.com/mercedes-w204-c63-amg-carbon-fiber-parts.html",
      imageUrl: null,
    },
    {
      id: "dp-hood",
      category: "exterior",
      type: "Aero",
      name: "IMP Performance Hood",
      brand: "DarwinPRO",
      description:
        "Forged or dry carbon hood featuring large vents to pull turbulent heat from the engine bay.",
      price: 1800,
      hpGain: null,
      torqueGain: null,
      specs: "Thermal extraction",
      productUrl: "https://www.eudmautosports.com/products/mercedes-benz-w204-c63-amg-imp-carbon-fiber-hood",
      imageUrl: null,
    },
    {
      id: "dp-rz-front-lip",
      category: "exterior",
      type: "Aero",
      name: "RZ Style CF Front Lip",
      brand: "DarwinPRO",
      description:
        "Front aerodynamic lip extending past the bumper edge to slice oncoming high-pressure air zones.",
      price: 750,
      hpGain: null,
      torqueGain: null,
      specs: "Front axle downforce",
      productUrl: "https://darwinproaero.com/collections/w204-coupe",
      imageUrl: null,
    },
    {
      id: "dp-rt-trunk",
      category: "exterior",
      type: "Aero",
      name: "RT Style CF Trunk Spoiler",
      brand: "DarwinPRO",
      description:
        "Mid-profile rear trunk spoiler balancing downforce and high-speed drag penalties.",
      price: 430,
      hpGain: null,
      torqueGain: null,
      specs: "Rear axle downforce",
      productUrl: "https://darwinproaero.com/collections/w204-coupe",
      imageUrl: null,
    },
    {
      id: "dp-bumper-caps",
      category: "exterior",
      type: "Cosmetic",
      name: "RZS Style CF Rear Bumper Caps",
      brand: "DarwinPRO",
      description:
        "Aesthetic carbon fiber covers refining the trailing edge of the rear bumper molding.",
      price: 350,
      hpGain: null,
      torqueGain: null,
      specs: "Aesthetic enhancement",
      productUrl: "https://darwinproaero.com/collections/w204-coupe",
      imageUrl: null,
    },
    {
      id: "mc-bootlid-coupe",
      category: "exterior",
      type: "Aero",
      name: "Coupe Bootlid Spoiler",
      brand: "Mode Carbon",
      description:
        "Vacuum-infused dry carbon bootlid spoiler maximizing torsional rigidity for rear downforce.",
      price: 595,
      hpGain: null,
      torqueGain: null,
      specs: "Rear axle downforce",
      productUrl: "https://www.modecarbon.com/product/w204-c63-coupe-bootlid-spoiler/",
      imageUrl: null,
    },
    {
      id: "mc-bootlid-sedan",
      category: "exterior",
      type: "Aero",
      name: "Sedan Bootlid Spoiler",
      brand: "Mode Carbon",
      description:
        "The sedan-specific profile of the vacuum-infused carbon fiber trunk spoiler.",
      price: 595,
      hpGain: null,
      torqueGain: null,
      specs: "Rear axle downforce",
      productUrl: "https://www.modecarbon.com/product/w204-c63-coupe-bootlid-spoiler/",
      imageUrl: null,
    },
    {
      id: "pd-black-edition-widebody",
      category: "exterior",
      type: "Aero",
      name: "C63 AMG \"Black Edition\" Widebody Kit",
      brand: "Prior Design",
      description:
        "Full widebody conversion featuring fender flares, front and rear bumpers, side skirts, and rear diffuser. Aggressive motorsport stance.",
      price: 20000,
      hpGain: null,
      torqueGain: null,
      specs: "Full widebody conversion",
      productUrl: "https://www.tuning-empire.com/prior-design-mercedes-benz-c63-amg-black-edition-widebody-kit.html",
      imageUrl: null,
    },
    {
      id: "sr66-black-series-widebody",
      category: "exterior",
      type: "Aero",
      name: "C W204 Black Series Widebody Kit",
      brand: "SR66 Design",
      description:
        "W204 wide body conversion kit inspired by the C63 Black Series. Includes fenders, bumpers, side skirts, and ducktail trunk spoiler.",
      price: 20000,
      hpGain: null,
      torqueGain: null,
      specs: "Includes ducktail trunk spoiler",
      productUrl: "https://sr66design.com/product/mercedes-benz-c-w204-wide-body-kit/",
      imageUrl: null,
    },
  ],
};
